version: '3'

services:
  postgres:
    image: postgres:latest  # Using the latest PostgreSQL version
    environment:
      POSTGRES_USER: claim_user
      POSTGRES_PASSWORD: claim_password
      POSTGRES_DB: claim_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - e-claim-network
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: claim_user
      DB_PASSWORD: claim_password
    command: ["start-dev"]                # Start Keycloak in development mode
    ports:
      - "8080:8080"                       # Keycloak admin console
    depends_on:
      - postgres
    networks:
      - e-claim-network   # Add the custom network
    volumes:
      - keycloak-data:/opt/keycloak/data

  claim-service:
    build: ./services/ClaimService  # Path to your Claim Service
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__ClaimDbConnection: "Host=postgres;Port=5432;Database=claim_db;Username=claim_user;Password=claim_password"
    ports:
      - "5016:8080"
    depends_on:
      - postgres
    networks:
      - e-claim-network

  kong:    
    image: kong:latest    
    environment:
      KONG_DATABASE: "off"                                # Disable the use of a database
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/kong.yml"  # Path to the declarative configuration file      
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001 # Kong Admin API (optional)
      KONG_LOG_LEVEL: debug   
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/kong.yml
    networks:
      - e-claim-network   # Add the custom network 

networks:
  e-claim-network:
    driver: bridge

volumes:
  postgres-data:
  keycloak-data:     # Declare the keycloak-data volume  